LIMS/Models/ReagentsViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LIMS.Models
{
    public class ReagentsSearchViewModel
    {
        public string Query { get; set; }

        public List<Reagent> Results { get; set; }
    }

    public class ReagentsCreateViewModel
    {
        [Display(Name = "Name")]
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        
        [Display(Name = "Quantity")]
        [Required]
        [Range(0, int.MaxValue)]
        public int Quantity { get; set; }
        
        [Display(Name = "Expires")]
        [Required]
        [DataType(DataType.Text)]
        [DisplayFormat(DataFormatString = Date.Placeholder, ApplyFormatInEditMode = true)]
        public Date ExpiryDate { get; set; }
        
        [Display(Name = "Manufacturer Code")]
        [Required]
        [StringLength(100)]
        public string ManufacturerCode { get; set; }
    }

    public class ReagentsEditViewModel : ReagentsCreateViewModel
    {
        public ReagentsEditViewModel()
        {
        }

        public ReagentsEditViewModel(Reagent reagent)
        {
            Reagent = reagent;
            Name = reagent.Name;
            Quantity = reagent.Quantity;
            ExpiryDate = reagent.ExpiryDate;
            ManufacturerCode = reagent.ManufacturerCode;
        }

        public Reagent Reagent { get; set; }
    }
}

LIMS/Controllers/ReagentsController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using LIMS.DataAccess;
using LIMS.Models;

namespace LIMS.Controllers
{
    [Authorize]
    public class ReagentsController : ControllerBase
    {
        public async Task<ActionResult> Index(string query)
        {
            if (string.IsNullOrWhiteSpace(query))
            {
                return View(new ReagentsSearchViewModel());
            }

            var model = new ReagentsSearchViewModel
            {
                Query = query,
                Results = await ReagentsDao.Find(this, query)
            };

            return View(model);
        }
        
        [Authorize(Roles = Roles.Privileged)]
        public ActionResult Create()
        {
            return View(new ReagentsCreateViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Roles.Privileged)]
        public async Task<ActionResult> Create(ReagentsCreateViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            Reagent newReagent = null;

            try
            {
                newReagent = await ReagentsDao.Create(this, model);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.ToString());
                return View(model);
            }

            return RedirectToAction("Details", new { reagent = newReagent?.ReagentId ?? 0 });
        }

        [Route("Reagents/{reagent:int}/")]
        public ActionResult Details(Reagent reagent)
        {
            if (reagent == null)
                return HttpNotFound();

            return View(reagent);
        }

        [Authorize(Roles = Roles.Privileged)]
        [Route("Reagents/{reagent:int}/Edit")]
        public ActionResult Edit(Reagent reagent)
        {
            if (reagent == null)
                return HttpNotFound();

            return View(new ReagentsEditViewModel(reagent));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Roles.Privileged)]
        [Route("Reagents/{reagent:int}/Edit")]
        public async Task<ActionResult> Edit(Reagent reagent, ReagentsEditViewModel model)
        {
            if (reagent == null)
                return HttpNotFound();

            if (!ModelState.IsValid)
                return View(model);

            try
            {
                await ReagentsDao.Update(this, reagent, model);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e);
                return View(model);
            }

            return RedirectToAction("Details", new { reagent = reagent.ReagentId });
        }

        [Authorize(Roles = Roles.Administrator)]
        [Route("Reagents/{reagent:int}/Delete")]
        public ActionResult Delete(Reagent reagent)
        {
            if (reagent == null)
                return HttpNotFound();

            return View(reagent);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Roles.Administrator)]
        [Route("Reagents/{reagent:int}/Delete")]
        public async Task<ActionResult> PostDelete(Reagent reagent)
        {
            if (reagent != null)
            {
                DbContext.Reagents.Remove(reagent);
                await DbContext.SaveChangesAsync();

                await LogAsync($"Deleted reagent ID {reagent.ReagentId}");
            }

            return RedirectToAction("Index");
        }
    }
}

LIMS/Views/Reagents/Create.cshtml
@model LIMS.Models.ReagentsCreateViewModel
@{
    ViewBag.Title = "Create reagent";
}

<h2>@ViewBag.Title</h2>
<hr />

@using (Html.BeginForm("Create", "Reagents", FormMethod.Post, new { role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group row">
        @Html.LabelFor(m => m.Name, new { @class = "col-md-2 col-form-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, null, new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row">
        @Html.LabelFor(m => m.Quantity, new { @class = "col-md-2 col-form-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Quantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Quantity, null, new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row">
        @Html.LabelFor(m => m.ExpiryDate, new { @class = "col-md-2 col-form-label" })
        <div class="col-md-10">
            <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                <div class="input-group-prepend" data-target="#datetimepicker1" data-toggle="datetimepicker">
                    <div class="input-group-text">
                        <span class="fa fa-calendar"></span>
                    </div>
                </div>
                @Html.EditorFor(m => m.ExpiryDate, new { htmlAttributes = new { @class = "form-control datetimepicker-input", data_target = "#datetimepicker1", placeholder = "DD/MM/YYYY" } })
            </div>
            @Html.ValidationMessageFor(model => model.ExpiryDate, null, new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row">
        @Html.LabelFor(m => m.ManufacturerCode, new { @class = "col-md-2 col-form-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.ManufacturerCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ManufacturerCode, null, new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row">
        <div class="offset-md-2 col-md-10">
            <input type="submit" class="btn btn-success" value="Create" />
        </div>
    </div>
}

<p>
    @Html.ActionLink("Back to reagents", "Index")
</p>


@section Styles {
    @Styles.Render("~/Content/datetimepicker")
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/datetimepicker")

    <script type="text/javascript">
        $(function ()
        {
            $('#datetimepicker1').datetimepicker({
                useCurrent: true,
                format: "DD/MM/YYYY",
                minDate: new Date(2000, 0),
                maxDate: new Date(2050, 0)
            });
        });
    </script>
}

LIMS/Views/Reagents/Delete.cshtml
@model LIMS.Models.Reagent

@{
    ViewBag.Title = "Delete reagent";
}

<h2>@ViewBag.Title</h2>
<h3>Are you sure you want to delete this reagent?</h3>
<hr />

<div>
    <dl class="row">
        <dt class="col-md-2 col-form-label">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-md-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-md-2 col-form-label">
            @Html.DisplayNameFor(model => model.ExpiryDate)
        </dt>
        <dd class="col-md-10">
            @Html.DisplayFor(model => model.ExpiryDate)
        </dd>
        <dt class="col-md-2 col-form-label">
            @Html.DisplayNameFor(model => model.ManufacturerCode)
        </dt>
        <dd class="col-md-10">
            @Html.DisplayFor(model => model.ManufacturerCode)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-secondary" })
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    }
</div>

<p>
    @Html.ActionLink("Back to reagents", "Index")
</p>

LIMS/Views/Reagents/Details.cshtml
@model LIMS.Models.Reagent
@{
    ViewBag.Title = "Reagent details";
}

<h2>@ViewBag.Title</h2>
<div class="btn-group">
    @if (User.IsPrivileged())
    {
        @Html.ActionLink("Edit", "Edit", "Reagents", new { reagent = Model.ReagentId }, new { @class = "btn btn-primary" })
    }
    @if (User.IsAdmin())
    {
        @Html.ActionLink("Delete", "Delete", "Reagents", new { reagent = Model.ReagentId }, new { @class = "btn btn-danger" })
    }
</div>
<hr />

<div>
    <dl class="row">
        <dt class="col-md-2 col-form-label">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-md-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-md-2 col-form-label">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class="col-md-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class="col-md-2 col-form-label">
            @Html.DisplayNameFor(model => model.AddedDate)
        </dt>
        <dd class="col-md-10">
            @Html.DisplayFor(model => model.AddedDate)
        </dd>
        <dt class="col-md-2 col-form-label">
            @Html.DisplayNameFor(model => model.ExpiryDate)
        </dt>
        <dd class="col-md-10">
            @Html.DisplayFor(model => model.ExpiryDate)
        </dd>
        <dt class="col-md-2 col-form-label">
            @Html.DisplayNameFor(model => model.ManufacturerCode)
        </dt>
        <dd class="col-md-10">
            @Html.DisplayFor(model => model.ManufacturerCode)
        </dd>
    </dl>
</div>

<p>
    @Html.ActionLink("Back to reagents", "Index")
</p>

LIMS/Views/Reagents/Edit.cshtml
@model LIMS.Models.ReagentsEditViewModel
@{
    ViewBag.Title = "Edit reagent";
}

<h2>@ViewBag.Title</h2>
<hr />

@using (Html.BeginForm(new { reagent = Model.Reagent.ReagentId }))
{
    @Html.AntiForgeryToken()

    <div>
        @Html.ValidationSummary(true, null, new { @class = "text-danger" })

        <div class="form-group row">
            @Html.LabelFor(model => model.Name, new { @class = "col-form-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(model => model.Quantity, new { @class = "col-form-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(model => model.ExpiryDate, new { @class = "col-form-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                    <div class="input-group-prepend" data-target="#datetimepicker1" data-toggle="datetimepicker">
                        <div class="input-group-text">
                            <span class="fa fa-calendar"></span>
                        </div>
                    </div>
                    @Html.EditorFor(m => m.ExpiryDate, new { htmlAttributes = new { @class = "form-control datetimepicker-input", data_target = "#datetimepicker1", placeholder = "DD/MM/YYYY" } })
                </div>
                @Html.ValidationMessageFor(model => model.ExpiryDate, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(model => model.ManufacturerCode, new { @class = "col-form-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.ManufacturerCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ManufacturerCode, null, new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <div class="offset-md-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<p>
    @Html.ActionLink("Back to reagent details", "Details", new { reagent = Model.Reagent.ReagentId })
</p>

@section Styles {
    @Styles.Render("~/Content/datetimepicker")
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/datetimepicker")

    <script type="text/javascript">
        $(function ()
        {
            $('#datetimepicker1').datetimepicker({
                format: "DD/MM/YYYY",
                minDate: new Date(2000, 0),
                maxDate: new Date(2050, 0)
            });
        });
    </script>
}

LIMS/Views/Reagents/Index.cshtml
@model LIMS.Models.ReagentsSearchViewModel
@{
    ViewBag.Title = "Reagents";
}

<h2>@ViewBag.Title</h2>

@if (User.IsPrivileged())
{
    @Html.ActionLink("Add", "Create", "Reagents", null, new { @class = "btn btn-success" })
}

<hr />

@using (Html.BeginForm("Index", "Reagents", FormMethod.Get, new { @class = "form-group" }))
{
    <div class="input-group">
        @Html.TextBoxFor(m => m.Query, new { @class = "form-control", placeholder = "Query" })
        <span class="input-group-append">
            <button type="submit" class="btn btn-primary">Search</button>
        </span>
    </div>
}

@if (Model.Results != null && Model.Results.Count == 0)
{
    <div class="alert alert-info">
        No reagents matched the query provided.
    </div>
}
else if (Model.Results != null)
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(m => m.Results.First().Name)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Results.First().Quantity)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Results.First().ExpiryDate)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Results.First().ManufacturerCode)
                </th>
                <th class="w-25">
                    Operations
                </th>
            </tr>
        </thead>

        @foreach (var result in Model.Results)
        {
            <tr>
                <td>
                    @Html.DisplayFor(m => result.Name)
                </td>
                <td>
                    @Html.DisplayFor(m => result.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(m => result.ExpiryDate)
                </td>
                <td>
                    @Html.DisplayFor(m => result.ManufacturerCode)
                </td>
                <td>
                    <div class="btn-group">
                        @Html.ActionLink("Details", "Details", "Reagents", new { reagent = result.ReagentId }, new { @class = "btn btn-secondary" })

                        @if (User.IsPrivileged())
                        {
                            @Html.ActionLink("Edit", "Edit", "Reagents", new { reagent = result.ReagentId }, new { @class = "btn btn-primary" })
                        }

                        @if (User.IsAdmin())
                        {
                            @Html.ActionLink("Delete", "Delete", "Reagents", new { reagent = result.ReagentId }, new { @class = "btn btn-danger" })
                        }
                    </div>
                </td>
            </tr>
        }
    </table>
}