LIMS/Models/TestsViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LIMS.Models
{
    public class TestsSearchViewModel
    {
        public string Query { get; set; }

        public List<Result> Results { get; set; }

        public class Result
        {
            [Display(Name = "Test Code")]
            public string TestId { get; set; }

            [Display(Name = "Name")]
            public string Name { get; set; }
        }
    }

    public class TestsCreateViewModel
    {
        [Display(Name = "Test Code")]
        [Required]
        [StringLength(20, MinimumLength = 3)]
        [RegularExpression("^[A-Z0-9]*$", ErrorMessage = "Test Code may only contain A-Z and 0-9.")]
        public string TestId { get; set; }
        
        [Display(Name = "Name")]
        [Required]
        [StringLength(100)]
        public string Name { get; set; }

        [Display(Name = "Description")]
        [Required]
        [StringLength(10000)]
        public string Description { get; set; }
    }

    public class TestsEditViewModel
    {
        public TestsEditViewModel()
        {
        }

        public TestsEditViewModel(Test test)
        {
            TestId = test.TestId;
            Name = test.Name;
            Description = test.Description;
        }

        [Display(Name = "Test Code")]
        [StringLength(20, MinimumLength = 3)]
        [RegularExpression("^[A-Z0-9]*$", ErrorMessage = "Test Code may only contain A-Z and 0-9.")]
        public string TestId { get; }

        [Display(Name = "Name")]
        [Required]
        [StringLength(100)]
        public string Name { get; set; }

        [Display(Name = "Description")]
        [Required]
        [StringLength(10000)]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
    }

    public class TestsDeleteViewModel
    {
        public Test Test { get; set; }

        public bool CannotDelete { get; set; }
    }

    public class TestsAddSampleViewModel
    {
        [Display(Name = "Description")]
        [Required]
        public string Description { get; set; }

        [Display(Name = "Taken")]
        [Required]
        [DataType(DataType.Text)]
        [DisplayFormat(DataFormatString = DateWithTime.Placeholder, ApplyFormatInEditMode = true)]
        public DateWithTime AddedDate { get; set; }
    }
}

LIMS/Controllers/TestsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using LIMS.DataAccess;
using LIMS.Models;

namespace LIMS.Controllers
{
    [Authorize]
    public class TestsController : ControllerBase
    {
        public async Task<ActionResult> Index(string query = null)
        {
            var results = await TestsDao.Find(this, query);
            if (results.Count == 0 && string.IsNullOrWhiteSpace(query))
                results = null;

            var model = new TestsSearchViewModel
            {
                Query = query,
                Results = results
            };

            return View(model);
        }
        
        [Route("Tests/Create")]
        [Authorize(Roles = Roles.Privileged)]
        public ActionResult Create()
        {
            return View(new TestsCreateViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Tests/Create")]
        [Authorize(Roles = Roles.Privileged)]
        public async Task<ActionResult> Create(TestsCreateViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            try
            {
                await TestsDao.Create(this, model);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e);
                return View(model);
            }

            return RedirectToAction("Details", new { test = model.TestId });
        }

        [Route("Tests/{test}")]
        public ActionResult Details(Test test)
        {
            if (test == null)
                return HttpNotFound();

            return View(test);
        }

        [Route("Tests/{test}/Edit")]
        [Authorize(Roles = Roles.Privileged)]
        public ActionResult Edit(Test test)
        {
            if (test == null)
                return HttpNotFound();

            return View(new TestsEditViewModel(test));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Tests/{test}/Edit")]
        [Authorize(Roles = Roles.Privileged)]
        public async Task<ActionResult> Edit(Test test, TestsEditViewModel model)
        {
            if (test == null)
                return RedirectToAction("Index");

            if (!ModelState.IsValid)
                return View(model);

            try
            {
                await TestsDao.Update(this, test, model);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e);
                return View(model);
            }

            return RedirectToAction("Details", new { test = test.TestId });
        }

        [Route("Tests/{test}/Delete")]
        [Authorize(Roles = Roles.Administrator)]
        public ActionResult Delete(Test test, bool cannotDelete = false)
        {
            if (test == null)
                return HttpNotFound();

            return View(new TestsDeleteViewModel
            {
                Test = test,
                CannotDelete = cannotDelete
            });
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Route("Tests/{test}/Delete")]
        [Authorize(Roles = Roles.Administrator)]
        public async Task<ActionResult> ConfirmDelete(Test test)
        {
            if (test != null)
            {
                try
                {
                    await TestsDao.Delete(this, test);
                }
                catch (Exception)
                {
                    return RedirectToAction("Delete", new { test = test.TestId, cannotDelete = true });
                }
            }

            return RedirectToAction("Index");
        }

        [Route("Tests/{test}/AddSample")]
        [Authorize(Roles = Roles.Privileged)]
        public ActionResult AddSample(Test test)
        {
            if (test == null)
                return HttpNotFound();

            return View(new TestsAddSampleViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Tests/{test}/AddSample")]
        [Authorize(Roles = Roles.Privileged)]
        public async Task<ActionResult> AddSample(Test test, TestsAddSampleViewModel model)
        {
            if (test == null)
                return HttpNotFound();

            if (!ModelState.IsValid)
                return View(model);

            long newSampleId;
            try
            {
                var sample = new Sample
                {
                    Test = test,
                    Description = model.Description,
                    AddedDate = model.AddedDate,
                };

                DbContext.Samples.Add(sample);
                await DbContext.SaveChangesAsync();

                newSampleId = sample.SampleId;
                await LogAsync($"Sample ID {newSampleId} created");
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e);
                return View(model);
            }

            return RedirectToAction("Details", "Samples", new { sample = newSampleId });
        }
    }
}

LIMS/Views/Tests/AddSample.cshtml
@model LIMS.Models.TestsAddSampleViewModel
@{
    ViewBag.Title = "Add sample to test";
}

<h2>@ViewBag.Title</h2>
<hr />

@using (Html.BeginForm("AddSample", "Tests", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, null, new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.AddedDate, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <div class="input-group date datetimepicker">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
                @Html.EditorFor(m => m.AddedDate, new { htmlAttributes = new { @class = "form-control", placeholder = "DD/MM/YYYY HH:MM:SS AM" } })
            </div>
            @Html.ValidationMessageFor(model => model.AddedDate, null, new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-success" value="Add" />
        </div>
    </div>
}

<p>
    @Html.ActionLink("Back to tests", "Index")
</p>


@section Styles {
    @Styles.Render("~/Content/datetimepicker")
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/datetimepicker")

    <script type="text/javascript">
        $(function ()
        {
            $('.datetimepicker').datetimepicker({
                useCurrent: true,
                format: "DD/MM/YYYY hh:mm:ss A",
                minDate: new Date(2000, 0),
                maxDate: new Date(2050, 0)
            });
        });
    </script>
}

LIMS/Views/Tests/Create.cshtml
@model LIMS.Models.TestsCreateViewModel
@{
    ViewBag.Title = "Create test";
}

<h2>@ViewBag.Title</h2>
<hr />

@using (Html.BeginForm("Create", "Tests", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(m => m.TestId, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.TestId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TestId, null, new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, null, new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Description, null, new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-success" value="Create" />
        </div>
    </div>
}

<p>
    @Html.ActionLink("Back to tests", "Index")
</p>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LIMS/Views/Tests/Delete.cshtml
@model LIMS.Models.TestsDeleteViewModel
@{
    ViewBag.Title = "Delete test";
}

<h2>@ViewBag.Title</h2>
<h3>Are you sure you want to delete this test?</h3>
<hr />

<div>
    <dl class="row">
        <dt class="col-md-2 col-form-label">
            @Html.DisplayNameFor(model => model.Test.TestId)
        </dt>
        <dd class="col-md-10">
            @Html.DisplayFor(model => model.Test.TestId)
        </dd>
        <dt class="col-md-2 col-form-label">
            @Html.DisplayNameFor(model => model.Test.Name)
        </dt>
        <dd class="col-md-10">
            @Html.DisplayFor(model => model.Test.Name)
        </dd>
        <dt class="col-md-2 col-form-label">
            @Html.DisplayNameFor(model => model.Test.Description)
        </dt>
        <dd class="col-md-10">
            <p>
                @Html.DisplayFor(model => model.Test.Description)
            </p>
        </dd>
    </dl>
    
    @if (Model.CannotDelete)
    {
        <div class="alert alert-danger">
            This test is being used by labs or samples and cannot be deleted until nothing references it.
        </div>
    }

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-secondary" })
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    }
</div>

<p>
    @Html.ActionLink("Back to tests", "Index")
</p>

LIMS/Views/Tests/Details.cshtml
@model LIMS.Models.Test
@{
    ViewBag.Title = "Test details";
}

<h2>@ViewBag.Title</h2>
<div class="btn-group">
    @if (User.IsPrivileged())
    {
        @Html.ActionLink("Add Sample", "AddSample", "Tests", new { test = Model.TestId }, new { @class = "btn btn-success" })
        @Html.ActionLink("Edit", "Edit", new { test = Model.TestId }, new { @class = "btn btn-primary" })
    }
    @if (User.IsAdmin())
    {
        @Html.ActionLink("Delete", "Delete", new { test = Model.TestId }, new { @class = "btn btn-danger" })
    }
</div>
<hr />

<div>
    <dl class="row">
        <dt class="col-md-2 col-form-label">
            @Html.DisplayNameFor(model => model.TestId)
        </dt>
        <dd class="col-md-10">
            @Html.DisplayFor(model => model.TestId)
        </dd>
        <dt class="col-md-2 col-form-label">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-md-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-md-2 col-form-label">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-md-10">
            <p>
                @Html.DisplayFor(model => model.Description)
            </p>
        </dd>
    </dl>
</div>

<p>
    @Html.ActionLink("Back to tests", "Index")
</p>

LIMS/Views/Tests/Edit.cshtml
@model LIMS.Models.TestsEditViewModel
@{
    ViewBag.Title = "Edit test";
}

<h2>@ViewBag.Title</h2>
<hr />

@using (Html.BeginForm(new { test = Model.TestId }))
{
    @Html.AntiForgeryToken()

    <div>
        @Html.ValidationSummary(true)
        
        <div class="form-group row">
            @Html.LabelFor(model => model.TestId, new { @class = "col-form-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(m => m.TestId)
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(model => model.Name, new { @class = "col-form-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(model => model.Description, new { @class = "col-form-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group row">
            <div class="offset-md-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<p>
    @Html.ActionLink("Back to tests", "Index")
</p>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LIMS/Views/Tests/Index.cshtml
@model LIMS.Models.TestsSearchViewModel
@{
    ViewBag.Title = "Tests";
}

<h2>@ViewBag.Title</h2>
@if (User.IsPrivileged())
{
    @Html.ActionLink("Create new", "Create", "Tests", null, new { @class = "btn btn-success" })
}
<hr />

@using (Html.BeginForm("Index", "Tests", FormMethod.Get, new { @class = "form-group" }))
{
    <div class="input-group">
        @Html.TextBoxFor(m => m.Query, new { @class = "form-control", placeholder = "Query" })
        <span class="input-group-append">
            <button type="submit" class="btn btn-primary">Search</button>
        </span>
    </div>
}

@if (Model.Results != null && Model.Results.Count == 0)
{
    <div class="alert alert-info">
        No tests matched the query provided.
    </div>
}
else if (Model.Results != null)
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(m => m.Results.First().TestId)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Results.First().Name)
                </th>
                <th class="w-25">
                    Operations
                </th>
            </tr>
        </thead>

        @foreach (var result in Model.Results)
        {
            <tr>
                <td>
                    @Html.DisplayFor(m => result.TestId)
                </td>
                <td>
                    @Html.DisplayFor(m => result.Name)
                </td>
                <td>
                    <div class="btn-group">
                        @Html.ActionLink("Details", "Details", "Tests", new { test = result.TestId }, new { @class = "btn btn-secondary" })
                        
                        @if (User.IsPrivileged())
                        {
                            @Html.ActionLink("Add Sample", "AddSample", "Tests", new { test = result.TestId }, new { @class = "btn btn-success" })
                            @Html.ActionLink("Edit", "Edit", "Tests", new { test = result.TestId }, new { @class = "btn btn-primary" })
                        }
                        
                        @if (User.IsAdmin())
                        {
                            @Html.ActionLink("Delete", "Delete", "Tests", new { test = result.TestId }, new { @class = "btn btn-danger" })
                        }
                    </div>
                </td>
            </tr>
        }
    </table>
}