LIMS/Models/SamplesViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LIMS.Models
{
    public class SamplesSearchViewModel
    {
        public string Query { get; set; }

        public List<Result> Results { get; set; }

        public class Result
        {
            public Sample Sample { get; set; }

            // can be null
            [Display(Name = "Assigned Lab")]
            public LabSample LabSample { get; set; }
        }
    }

    public class SamplesDetailsViewModel
    {
        public Sample Sample { get; set; }
    }

    public class SamplesCreateViewModel
    {
        [Display(Name = "Test Code")]
        [Required]
        public string TestId { get; set; }

        [Display(Name = "Description")]
        [Required]
        public string Description { get; set; }

        [Display(Name = "Taken")]
        [Required]
        [DataType(DataType.Text)]
        [DisplayFormat(DataFormatString = DateWithTime.Placeholder, ApplyFormatInEditMode = true)]
        public DateWithTime AddedDate { get; set; }
    }

    public class SamplesEditViewModel : SamplesCreateViewModel
    {
        public Sample Sample { get; set; }

        public SamplesEditViewModel()
        {
        }

        public SamplesEditViewModel(Sample sample)
        {
            Sample = sample;
            TestId = sample.TestId;
            Description = sample.Description;
            AddedDate = sample.AddedDate;
        }
    }
}

LIMS/Controllers/LabsController.cs
using System;
using System.Data.Entity;
using System.Threading.Tasks;
using System.Web.Mvc;
using LIMS.DataAccess;
using LIMS.Models;
using Microsoft.AspNet.Identity;

namespace LIMS.Controllers
{
    [Authorize]
    public class LabsController : ControllerBase
    {
        public async Task<ActionResult> Index(string query = null)
        {
            var results = await LabsDao.Find(this, query);
            if (results.Count == 0 && string.IsNullOrWhiteSpace(query))
                results = null;

            var model = new LabsSearchViewModel
            {
                Query = query,
                Results = results
            };

            return View(model);
        }

        [Authorize(Roles = Roles.Privileged)]
        public ActionResult Create()
        {
            return View(new LabsCreateViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Roles.Privileged)]
        public async Task<ActionResult> Create(LabsCreateViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            try
            {
                await LabsDao.Create(this, model);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.ToString());
                return View(model);
            }

            return RedirectToAction("Index");
        }
        
        [Route("Labs/{lab:int}/")]
        [LabMember]
        public ActionResult Details(Lab lab)
        {
            var userId = HttpContext.User.Identity.GetUserId();
            return View(new LabsDetailsViewModel
            {
                Lab = lab,
                IsLabManager = lab.UserIsLabManager(userId)
            });
        }

        [Route("Labs/{lab:int}/Edit")]
        [LabMember(LabManager = true)]
        public ActionResult Edit(Lab lab)
        {
            return View(new LabsEditViewModel(lab));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Labs/{lab:int}/Edit")]
        [LabMember(LabManager = true)]
        public async Task<ActionResult> Edit(Lab lab, LabsEditViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            
            try
            {
                await LabsDao.Update(this, lab, model);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.ToString());
                return View(model);
            }

            return RedirectToAction("Details", new { lab = lab.LabId });
        }

        [Route("Labs/{lab:int}/Delete")]
        [Authorize(Roles = Roles.Administrator)]
        public ActionResult Delete(Lab lab)
        {
            return View(lab);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Labs/{lab:int}/Delete")]
        [Authorize(Roles = Roles.Administrator)]
        public async Task<ActionResult> ConfirmDelete(Lab lab)
        {
            await LabsDao.Delete(this, lab);

            return RedirectToAction("Index");
        }

        [Route("Labs/{lab:int}/Report")]
        [Authorize(Roles = Roles.Privileged)]
        public async Task<ActionResult> Report(Lab lab)
        {
            return View(await LabsDao.GenerateReport(this, lab));
        }
        
        /**************************************************************/

        [Route("Labs/{lab:int}/Members")]
        [LabMember]
        public async Task<ActionResult> Members(Lab lab)
        {
            var userId = HttpContext.User.Identity.GetUserId();
            var members = await LabsDao.ListMembers(this, lab.LabId);

            var model = new LabsMembersViewModel
            {
                Lab = lab,
                Members = members,
                IsLabManager = lab.UserIsLabManager(userId)
            };
            
            return View(model);
        }
        
        [Route("Labs/{lab:int}/Members/Add")]
        [LabMember(LabManager = true)]
        public async Task<ActionResult> AddMember(Lab lab, string query = null)
        {
            var model = new LabsAddMemberViewModel
            {
                Lab = lab,
            };

            if (string.IsNullOrWhiteSpace(query))
            {
                return View(model);
            }

            model.Query = query;
            model.Results = await LabsDao.ListAddableMembers(this, lab.LabId, query);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Labs/{lab:int}/Members/Add")]
        [LabMember(LabManager = true)]
        public async Task<ActionResult> PostAddMember(Lab lab, string userId)
        {
            await LabsDao.AddMember(this, lab.LabId, userId);
            return RedirectToAction("Members", new { lab = lab.LabId });
        }

        [Route("Labs/{lab:int}/Members/Remove")]
        [LabMember(LabManager = true)]
        public async Task<ActionResult> RemoveMember(Lab lab, string userId)
        {
            var user = await UserManager.FindByIdAsync(userId);
            if (user == null)
                return RedirectToAction("Members", new { lab = lab.LabId });

            var model = new LabsRemoveMemberViewModel
            {
                Lab = lab,
                UserId = userId,
                UserName = user.UserName
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Labs/{lab:int}/Members/Remove")]
        [LabMember(LabManager = true)]
        public async Task<ActionResult> PostRemoveMember(Lab lab, string userId)
        {
            await LabsDao.RemoveMember(this, lab.LabId, userId);
            return RedirectToAction("Members", new { lab = lab.LabId });
        }

        /**************************************************************/

        [Route("Labs/{lab:int}/Reagents")]
        [LabMember]
        public async Task<ActionResult> Reagents(Lab lab)
        {
            var userId = HttpContext.User.Identity.GetUserId();
            var results = await LabsDao.ListReagents(this, lab.LabId);
            var model = new LabsReagentsViewModel
            {
                Lab = lab,
                UsedReagents = results,
                IsLabManager = lab.UserIsLabManager(userId)
            };
            
            return View(model);
        }

        [Route("Labs/{lab:int}/Reagents/Add")]
        [LabMember]
        public async Task<ActionResult> AddReagent(Lab lab, string query = null)
        {
            var model = new LabsAddReagentViewModel
            {
                Lab = lab,
            };

            if (string.IsNullOrWhiteSpace(query))
            {
                return View(model);
            }
            
            model.Query = query;
            model.Results = await ReagentsDao.Find(this, query);
            return View(model);
        }

        [Route("Labs/{lab:int}/Reagents/Add/{reagent:int}")]
        [LabMember]
        public ActionResult ConfirmAddReagent(Lab lab, Reagent reagent)
        {
            if (reagent == null)
                return RedirectToAction("Reagents", new { lab = lab.LabId });

            return View(new LabsConfirmAddReagentViewModel
            {
                Lab = lab,
                Reagent = reagent,
                Quantity = 1
            });
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Labs/{lab:int}/Reagents/Add/{reagent:int}")]
        [LabMember]
        public async Task<ActionResult> ConfirmAddReagent(Lab lab, Reagent reagent, LabsConfirmAddReagentViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            
            try
            {
                await LabsDao.AddReagent(this, lab, reagent, model.Quantity);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e);
                return View(model);
            }

            return RedirectToAction("Reagents", new { lab = lab.LabId });
        }

        [Route("Labs/{lab:int}/Reagents/Remove/{usedReagentId:int}")]
        [LabMember(LabManager = true)]
        public async Task<ActionResult> RemoveReagent(Lab lab, [System.Web.Http.FromUri] long usedReagentId)
        {
            var usedReagent = await DbContext.UsedReagents
                .Include(ur => ur.Reagent)
                .FirstOrDefaultAsync(ur => ur.UsedReagentId == usedReagentId);

            if (usedReagent == null)
                return RedirectToAction("Reagents", new { lab = lab.LabId });

            return View(new LabsRemoveReagentViewModel
            {
                Lab = lab,
                Reagent = usedReagent.Reagent,
                UsedReagentId = usedReagentId
            });
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Labs/{lab:int}/Reagents/Remove/{usedReagentId:int}")]
        [LabMember(LabManager = true)]
        public async Task<ActionResult> PostRemoveReagent(Lab lab, [System.Web.Http.FromUri] long usedReagentId, LabsRemoveReagentViewModel model)
        {
            var usedReagent = await DbContext.UsedReagents
                .Include(ur => ur.Reagent)
                .FirstOrDefaultAsync(ur => ur.UsedReagentId == usedReagentId);

            if (usedReagent == null)
                return RedirectToAction("Reagents", new { lab = lab.LabId });

            model.Lab = lab;
            model.Reagent = usedReagent.Reagent;

            if (!ModelState.IsValid)
                return View("RemoveReagent", model);

            try
            {
                await LabsDao.RemoveReagent(this, lab.LabId, usedReagentId, model.ReturnQuantity);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e);

LIMS/Controllers/SamplesController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using LIMS.DataAccess;
using LIMS.Models;

namespace LIMS.Controllers
{
    [Authorize]
    public class SamplesController : ControllerBase
    {
        public async Task<ActionResult> Index(string query = null)
        {
            if (string.IsNullOrWhiteSpace(query))
            {
                return View(new SamplesSearchViewModel());
            }

            var model = new SamplesSearchViewModel
            {
                Query = query,
                Results = await SamplesDao.Find(this, query)
            };

            return View(model);
        }

        [Authorize(Roles = Roles.Privileged)]
        public ActionResult Create()
        {
            return View(new SamplesCreateViewModel());
        }

        [HttpPost]
        [Authorize(Roles = Roles.Privileged)]
        public async Task<ActionResult> Create(SamplesCreateViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            Sample sample;
            try
            {
                sample = await SamplesDao.Create(this, model);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e);
                return View(model);
            }

            return RedirectToAction("Details", new { sample = sample.SampleId });
        }

        [Route("Samples/{sample:int}/")]
        public ActionResult Details(Sample sample)
        {
            if (sample == null)
                return HttpNotFound();

            return View(new SamplesDetailsViewModel
            {
                Sample = sample
            });
        }

        [Route("Samples/{sample:int}/Edit")]
        [Authorize(Roles = Roles.Privileged)]
        public ActionResult Edit(Sample sample)
        {
            if (sample == null)
                return HttpNotFound();

            return View(new SamplesEditViewModel(sample));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Samples/{sample:int}/Edit")]
        [Authorize(Roles = Roles.Privileged)]
        public async Task<ActionResult> Edit(Sample sample, SamplesEditViewModel model)
        {
            if (sample == null)
                return HttpNotFound();
            
            if (!ModelState.IsValid)
                return View(model);

            try
            {
                await SamplesDao.Update(this, sample, model);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e);
                return View(model);
            }

            return RedirectToAction("Details", new { sample = sample.SampleId });
        }

        [Route("Samples/{sample:int}/Delete")]
        [Authorize(Roles = Roles.Administrator)]
        public ActionResult Delete(Sample sample)
        {
            if (sample == null)
                return HttpNotFound();

            return View(sample);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Route("Samples/{sample:int}/Delete")]
        [Authorize(Roles = Roles.Administrator)]
        public async Task<ActionResult> ConfirmDelete(Sample sample)
        {
            if (sample != null)
            {
                await SamplesDao.Delete(this, sample);
            }

            return RedirectToAction("Index");
        }
    }
}

LIMS/Views/Samples/Create.cshtml
@model LIMS.Models.SamplesCreateViewModel
@{
    ViewBag.Title = "Add sample";
}

<h2>@ViewBag.Title</h2>
<hr />

@using (Html.BeginForm("Create", "Samples", FormMethod.Post, new { @role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group row">
        @Html.LabelFor(m => m.TestId, new { @class = "col-md-2 col-form-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.TestId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TestId, null, new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row">
        @Html.LabelFor(m => m.Description, new { @class = "col-md-2 col-form-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, null, new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row">
        @Html.LabelFor(m => m.AddedDate, new { @class = "col-md-2 col-form-label" })
        <div class="col-md-10">
            <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                <div class="input-group-prepend" data-target="#datetimepicker1" data-toggle="datetimepicker">
                    <div class="input-group-text">
                        <span class="fa fa-calendar"></span>
                    </div>
                </div>
                @Html.EditorFor(m => m.AddedDate, new { htmlAttributes = new { @class = "form-control datetimepicker-input", data_target = "#datetimepicker1", placeholder = "DD/MM/YYYY HH:MM:SS AM" } })
            </div>
            @Html.ValidationMessageFor(model => model.AddedDate, null, new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row">
        <div class="offset-md-2 col-md-10">
            <input type="submit" class="btn btn-success" value="Add" />
        </div>
    </div>
}

<p>
    @Html.ActionLink("Back to samples", "Index")
</p>


@section Styles {
    @Styles.Render("~/Content/datetimepicker")
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/datetimepicker")

    <script type="text/javascript">
        $(function ()
        {
            $('#datetimepicker1').datetimepicker({
                useCurrent: true,
                format: "DD/MM/YYYY h:mm:ss A",
                minDate: new Date(2000, 0),
                maxDate: new Date(2050, 0)
            });
        });
    </script>
}

LIMS/Views/Samples/Delete.cshtml
@model LIMS.Models.Sample
@{
    ViewBag.Title = "Delete sample";
}

<h2>@ViewBag.Title</h2>
<h3>Are you sure you want to delete this sample?</h3>
<hr />

<div>
    <dl class="row">
        <dt class="col-md-2 col-form-label">
            @Html.DisplayNameFor(model => model.TestId)
        </dt>
        <dd class="col-md-10">
            @Html.ActionLink(Model.TestId, "Details", "Tests", new { test = Model.TestId }, null)
        </dd>
        <dt class="col-md-2 col-form-label">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-md-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-md-2 col-form-label">
            @Html.DisplayNameFor(model => model.AddedDate)
        </dt>
        <dd class="col-md-10">
            @Html.DisplayFor(model => model.AddedDate)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-secondary" })
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    }
</div>

<p>
    @Html.ActionLink("Back to samples", "Index")
</p>

LIMS/Views/Samples/Details.cshtml
@model LIMS.Models.SamplesDetailsViewModel
@{
    ViewBag.Title = "Sample details";
}

<h2>@ViewBag.Title</h2>
<div class="btn-group">
    @if (User.IsPrivileged())
    {
        @Html.ActionLink("Edit", "Edit", "Samples", new { sample = Model.Sample.SampleId }, new { @class = "btn btn-primary" })
    }
    @if (User.IsAdmin())
    {
        @Html.ActionLink("Delete", "Delete", "Samples", new { sample = Model.Sample.SampleId }, new { @class = "btn btn-danger" })
    }
</div>
<hr />

<div>
    <dl class="row">
        <dt class="col-md-2 col-form-label">
            @Html.DisplayNameFor(model => model.Sample.Description)
        </dt>
        <dd class="col-md-10">
            @Html.DisplayFor(model => model.Sample.Description)
        </dd>
        <dt class="col-md-2 col-form-label">
            @Html.DisplayNameFor(model => model.Sample.AddedDate)
        </dt>
        <dd class="col-md-10">
            @Html.DisplayFor(model => model.Sample.AddedDate)
        </dd>
        <dt class="col-md-2 col-form-label">
            @Html.DisplayNameFor(model => model.Sample.Test)
        </dt>
        <dd class="col-md-10">
            @Html.ActionLink(Model.Sample.TestId, "Details", "Tests", new { test = Model.Sample.TestId }, null)
        </dd>
    </dl>
</div>

<p>
    @Html.ActionLink("Back to samples", "Index")
</p>

LIMS/Views/Samples/Edit.cshtml
@model LIMS.Models.SamplesEditViewModel
@{
    ViewBag.Title = "Edit sample";
}

<h2>@ViewBag.Title</h2>
<hr />

@using (Html.BeginForm(new { sample = Model.Sample.SampleId }))
{
    @Html.AntiForgeryToken()

    <div>
        @Html.ValidationSummary(true, null, new { @class = "text-danger" })

        <div class="form-group row">
            @Html.LabelFor(model => model.TestId, new { @class = "col-form-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.TestId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TestId, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(model => model.Description, new { @class = "col-form-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(model => model.AddedDate, new { @class = "col-form-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                    <div class="input-group-prepend" data-target="#datetimepicker1" data-toggle="datetimepicker">
                        <div class="input-group-text">
                            <span class="fa fa-calendar"></span>
                        </div>
                    </div>
                    @Html.EditorFor(m => m.AddedDate, new { htmlAttributes = new { @class = "form-control datetimepicker-input", data_target = "#datetimepicker1", placeholder = "DD/MM/YYYY HH:MM:SS AM" } })
                </div>
                @Html.ValidationMessageFor(model => model.AddedDate, null, new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <div class="offset-md-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<p>
    @Html.ActionLink("Back to sample details", "Details", new { reagent = Model.Sample.SampleId })
</p>

@section Styles {
    @Styles.Render("~/Content/datetimepicker")
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/datetimepicker")

    <script type="text/javascript">
        $(function ()
        {
            $('#datetimepicker1').datetimepicker({
                format: "DD/MM/YYYY h:mm:ss A",
                minDate: new Date(2000, 0),
                maxDate: new Date(2050, 0)
            });
        });
    </script>
}

LIMS/Views/Samples/Index.cshtml
@model LIMS.Models.SamplesSearchViewModel
@{
    ViewBag.Title = "Samples";
}

<h2>@ViewBag.Title</h2>
@if (User.IsPrivileged())
{
    @Html.ActionLink("Add", "Create", "Samples", null, new { @class = "btn btn-success" })
}
<hr />

@using (Html.BeginForm("Index", "Samples", FormMethod.Get, new { @class = "form-group" }))
{
    <div class="input-group">
        @Html.TextBoxFor(m => m.Query, new { @class = "form-control", placeholder = "Query" })
        <span class="input-group-append">
            <button type="submit" class="btn btn-primary">Search</button>
        </span>
    </div>
}

@if (Model.Results != null && Model.Results.Count == 0)
{
    <div class="alert alert-info">
        No samples matched the query provided.
    </div>
}
else if (Model.Results != null)
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(m => m.Results.First().Sample.TestId)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Results.First().Sample.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Results.First().Sample.AddedDate)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Results.First().LabSample)
                </th>
                <th class="w-25">
                    Operations
                </th>
            </tr>
        </thead>

        @foreach (var result in Model.Results)
        {
            <tr>
                <td>
                    @Html.ActionLink(result.Sample.TestId, "Details", "Tests", new { test = result.Sample.TestId }, null)
                </td>
                <td>
                    @Html.DisplayFor(m => result.Sample.Description)
                </td>
                <td>
                    @Html.DisplayFor(m => result.Sample.AddedDate)
                </td>
                <td>
                    @if (result.LabSample != null)
                    {
                        @Html.ActionLink("Open", "Details", "Labs", new { lab = result.LabSample.LabId }, new { @class = "btn btn-info" })
                    }
                </td>
                <td>
                    <span class="btn-group">
                        @Html.ActionLink("Details", "Details", "Samples", new { sample = result.Sample.SampleId }, new { @class = "btn btn-secondary" })
                        
                        @if (User.IsPrivileged())
                        {
                            @Html.ActionLink("Edit", "Edit", "Samples", new { sample = result.Sample.SampleId }, new { @class = "btn btn-primary" })
                        }

                        @if (User.IsAdmin())
                        {
                            @Html.ActionLink("Delete", "Delete", "Samples", new { sample = result.Sample.SampleId }, new { @class = "btn btn-danger" })
                        }
                    </span>
                </td>
            </tr>
        }
    </table>
}